export const SITIO = {
  nombre: 'Academia de Matemáticas MATRIX',
  nombreCorto: 'MATRIX',
  telefono: '922977802',
  whatsapp: 'https://wa.me/51922977802',
  ubicacion: 'Cabanillas, Perú',
  lugarInscripcion: 'Plaza de Armas – Cabanillas',
  lugarClases: 'Colegio Mixto de Cabanillas',
  urlMapa: 'https://maps.google.com/?q=Plaza+de+Armas+Cabanillas+Puno+Peru',
};

export const CURSOS = {
  primaria: [
    { nombre: 'Álgebra', icono: '' },
    { nombre: 'Aritmética', icono: '' },
    { nombre: 'Geometría', icono: '' },
    { nombre: 'Razonamiento Matemático', icono: '' },
    { nombre: 'Física', icono: '⚡' },
  ],
  secundaria: [
    { nombre: 'Geometría', icono: '' },
    { nombre: 'Álgebra', icono: '' },
    { nombre: 'Trigonometría', icono: '' },
    { nombre: 'Aritmética', icono: '' },
    { nombre: 'Física', icono: '⚡' },
    { nombre: 'Razonamiento Matemático', icono: '' },
  ],
  preuniversitario: [
    { nombre: 'Álgebra', icono: '' },
    { nombre: 'Geometría', icono: '' },
    { nombre: 'Trigonometría', icono: '' },
    { nombre: 'Aritmética', icono: '' },
    { nombre: 'Física', icono: '⚡' },
    { nombre: 'Química', icono: '' },
    { nombre: 'Razonamiento Matemático', icono: '' },
    { nombre: 'Razonamiento Verbal', icono: '' },
  ],
};

export const CICLOS = {
  sabatino: {
    id: 'sabatino',
    nombre: 'Ciclo Sabatino',
    emoji: '',
    color: '#00d4ff',
    etiqueta: 'INSCRIPCIONES ABIERTAS',
    duracion: '4 semanas',
    totalHoras: '16 horas',
    niveles: ['primaria', 'secundaria', 'preuniversitario'],
    precio: 47,
    etiquetaPrecio: 'S/ 47',
    subPrecio: 'mensual',
    turnos: null,
    inicioInscripcion: 'Jueves 14 de mayo',
    finInscripcion: 'Viernes 22 de mayo',
    inicioClases: '23 de mayo',
    estadisticas: [
      { numero: '4', etiqueta: 'Semanas' },
      { numero: '16h', etiqueta: 'Total clases' },
      { numero: '3', etiqueta: 'Niveles' },
      { numero: 'S/47', etiqueta: 'Mensual' },
    ],
    descripcion: 'Reforzamiento semanal cada sábado. Ideal para estudiantes que necesitan apoyo constante durante el año escolar.',
  },
  verano: {
    id: 'verano',
    nombre: 'Ciclo Vacacional Verano 2027',
    emoji: '☀️',
    color: '#ff6b00',
    etiqueta: 'INSCRIPCIONES ABIERTAS',
    duracion: '6 semanas',
    totalHoras: '72 horas',
    niveles: ['primaria', 'secundaria', 'preuniversitario'],
    precio: 167,
    etiquetaPrecio: 'S/ 167',
    subPrecio: 'ciclo completo',
    turnos: ['Mañana', 'Tarde'],
    inicioInscripcion: '1 de diciembre',
    finInscripcion: '10 de enero',
    inicioClases: '11 de enero',
    estadisticas: [
      { numero: '6', etiqueta: 'Semanas' },
      { numero: '72h', etiqueta: 'Total clases' },
      { numero: '3', etiqueta: 'Niveles' },
      { numero: 'S/167', etiqueta: 'Ciclo completo' },
    ],
    descripcion: 'Preparación intensiva durante las vacaciones de verano. Dos turnos disponibles para mayor comodidad.',
  },
  anual: {
    id: 'anual',
    nombre: 'Ciclo Anual',
    emoji: '',
    color: '#7c3aed',
    etiqueta: 'PRÓXIMAMENTE',
    duracion: '10 horas / semana',
    totalHoras: '10h por semana',
    niveles: ['secundaria', 'preuniversitario'],
    precio: 87,
    etiquetaPrecio: 'S/ 87',
    subPrecio: 'mensual',
    turnos: ['Tarde'],
    inicioInscripcion: 'Próximamente',
    finInscripcion: 'Próximamente',
    inicioClases: 'Próximamente',
    estadisticas: [
      { numero: '10h', etiqueta: 'Por semana' },
      { numero: '2', etiqueta: 'Niveles' },
      { numero: 'Tarde', etiqueta: 'Turno' },
      { numero: 'S/87', etiqueta: 'Mensual' },
    ],
    descripcion: 'Preparación continua a lo largo del año para secundaria y preuniversitario. Turno tarde.',
  },
};

export const INFO_NIVELES = [
  { id: 'primaria', nombre: 'Primaria', emoji: '', color: '#00d4ff' },
  { id: 'secundaria', nombre: 'Secundaria', emoji: '', color: '#ff6b00' },
  { id: 'preuniversitario', nombre: 'Preuniversitario', emoji: '', color: '#7c3aed' },
];
